import React, { Component } from 'react';
import './Database.css';

export default class Home extends Component {
  render() {
    return (
      <div className="db container">
        <h3>Database available</h3>
        <br />
        <br />
        <p><p1>1. Apple-> Apple scab</p1> : Apple scab is a fungal disease affecting the leaves and fruit to the point where the tree loses its leaves, and the apples are so blemished that they become unfit for eating.</p>
        <p><p1>2. Apple-> Black rot</p1> : Black rot is a disease of apples that infects fruit, leaves, and bark caused by the fungus Botryosphaeria obtusa. It can also jump to healthy tissue on pear or quince trees but is typically a secondary fungus of weak or dead tissues in other plants.</p>
        <p><p1>3. Apple-> Cedar apple rust</p1> : Cedar apple rust (Gymnosporangium juniperi-virginianae) is a fungal disease that requires juniper plants to complete its complicated two year life-cycle. Spores overwinter as a reddish-brown gall on young twigs of various juniper species.In early spring, during wet weather, these galls swell and bright orange masses of spores are blown by the wind where they infect susceptible apple and crab-apple trees.</p>
        <p><p1>4. Cherry-> Powdery mildew</p1> : Powdery mildew of sweet and sour cherry is caused by Podosphaera clandestina, an obligate biotrophic fungus. Mid- and late-season sweet cherry (Prunus avium) cultivars are commonly affected, rendering them unmarketable due to the covering of white fungal growth on the cherry surface.</p>
        <p><p1>5. Corn-> Cercospora leaf spot (Gray leaf spot)</p1> : Gray leaf spot, caused by the fungus Cercospora zeae-maydis, occurs virtually every growing season. If conditions favor disease development, economic losses can occur. Symptoms first appear on lower leaves about two to three weeks before tasseling.</p>
        <p><p1>6. Corn-> Common rust</p1> : Common rust is caused by the fungus Puccinia sorghi and occurs every growing season. It is seldom a concern in hybrid corn. Rust pustules usually first appear in late June. Early symptoms of common rust are chlorotic flecks on the leaf surface. These soon develop into powdery, brick-red pustules as the spores break through the leaf surface. </p>
        <p><p1>7. Corn-> Northern Leaf Blight</p1> : Northern corn leaf blight caused by the fungus Exerohilum turcicum is a common leaf blight found in New York. If lesions begin early (before silking), crop loss can result. Late infections may have less of an impact on yield. Northern corn leaf blight is favored by wet humid cool weather typically found later in the growing season.</p>
        <p><p1>8. Grape-> Black rot</p1> :  The black rot is caused by the fungus Guignardia bidwellii. The fungus can infect the leaves, shoots, berries, tendrils, rachises and cluster stems (peduncles) of grapes. If the disease is not managed early in the season, the impact on grape clusters can be devastating, resulting in complete crop losses.</p>
        <p><p1>9. Grape-> Esca (Black Measles)</p1> : Grapevine measles, also called esca, black measles or Spanish measles, has long plagued grape growers with its cryptic expression of symptoms and, for a long time, a lack of identifiable causal organism(s). The name ‘measles’ refers to the superficial spots found on the fruit</p>
        <p><p1>10. Grape-> Leaf blight (Isariopsis Leaf Spot)</p1> : Leaf blight caused by the fungus Pseudocercospora vitis. Initially lesions are dull red to brown in color turn black later. If disease is severe this lesions may coalesce. On berries we can see symptom similar to black rot but the entire clusters will collapse.</p>
        <p><p1>11. Orange-> Haunglongbing (Citrus greening)</p1> : Huanglongbing (HLB) or citrus greening is the most severe citrus disease, currently devastating the citrus industry worldwide. The presumed causal bacterial agent Candidatus Liberibacter spp. affects tree health as well as fruit development, ripening and quality of citrus fruits and juice.</p>
        <p><p1>12. Peach-> Bacterial spot</p1> : Bacterial spot caused by Xanthomonas arboricola pv. pruni (XAP). The disease’s symptoms include fruit spots, leaf spots and twig cankers. Fruit symptoms include pitting, cracking, gumming and watersoaked tissue. Fruit infected by bacterial spot are more susceptible to other fruit diseases such as brown rot and rhizopus, as well as infestations by insects.</p>
        <p><p1>13. Pepper ,bell-> Bacterial spot</p1> : Bacterial spot is caused by the bacterium Xanthomonas campestris pv. vesicatoria.  A mild case of bacterial spot causes prominent necrotic spots on leaves; a severe case can cause premature leaf drop and spotting of stems and pods that results in unmarketable fruit. Bacterial spot is difficult to control when frequent rains and moist conditions prevail.</p>
        <p><p1>14. Potato-> Early blight</p1> : Early blight of potato is caused by the fungal pathogen Alternaria solani. The disease affects leaves, stems and tubers and can reduce yield, tuber size, storability of tubers, quality of fresh-market and processing tubers and marketability of the crop.</p>
        <p><p1>15. Potato-> Late blight</p1> : Late blight is caused by the funguslike oomycete pathogen Phytophthora infestans. This potentially devastating disease can infect potato foliage and tubers at any stage of crop development. The first symptoms of late blight in the field are small, light to dark green, circular to irregular-shaped water-soaked spots.</p>
        <p><p1>16. Squash-> Powdery mildew</p1> : Powdery mildew, mainly caused by the fungus Podosphaera xanthii. Powdery mildew can cause premature death of leaves, and reduce yield and fruit quality.The first sign of powdery mildew is pale yellow leaf spots.White powdery spots can form on both upper and lower leaf surfaces, and quickly expand into large blotches.</p>
        <p><p1>17. Strawberry-> Leaf scorch</p1> : Leaf scorch is caused by Diplocarpon earlianum.  This ascomycete produces disk-shaped, dark brown to black apothecia on advanced-stage lesions on strawberry leaves and leaf residues.</p>
        <p><p1>18. Tomato-> Bacterial spot</p1> : Bacterial spot is caused by four species of Xanthomonas and occurs worldwide wherever tomatoes are grown. Bacterial spot causes leaf and fruit spots, which leads to defoliation, sun-scalded fruit, and yield loss. </p>
        <p><p1>19. Tomato-> Early blight</p1> : Early blight is caused by the fungus Alternaria solani. It can affect almost all parts of the tomato plants, including the leaves, stems, and fruits. The plants may not die, but they will be weakened and will set fewer tomatoes than normal. Early blight generally attacks older plants, but it can also occur on seedlings.</p>
        <p><p1>20. Tomato-> Late blight</p1> : Late blight is a potentially devastating disease of tomato and potato, infecting leaves, stems and fruits of tomato plants. The disease spreads quickly in fields and can result in total crop failure if untreated.</p>
        <p><p1>21. Tomato-> Leaf Mold</p1> : Tomato leaf mold is a fungal disease that can develop when there are extended periods of leaf wetness and the relative humidity is high (greater than 85 percent). Due to this moisture requirement, the disease is seen primarily in hoophouses and greenhouses. Symptoms of disease include yellow spots on the upper leaf surface. Discrete masses of olive-green spores can be seen on the underside of the affected leaves.</p>
        <p><p1>22. Tomato-> Septoria leaf spot</p1> : Septoria leaf spot is caused by a fungus, Septoria lycopersici. It is one of the most destructive diseases of tomato foliage and is particularly severe in areas where wet, humid weather persists for extended periods. Septoria leaf spot usually appears on the lower leaves after the first fruit sets. Spots are circular, about 1/16 to 1/4 inch in diameter with dark brown margins and tan to gray centers with small black fruiting structures.</p>
        <p><p1>23. Tomato-> Spider mites (Two-spotted spider mite)</p1> : Two‑spotted spider mites are occasional pests that can cause serious damage to some vegetable crops during hot dry weather. Mites can injure tomatoes, beans, muskmelons, watermelons, and sweet corn. Extended periods of hot, dry weather favors mite buildups. Infestations usually first occur at the edge of a field, typically near rank weed growth or dirt roads.</p>
        <p><p1>24. Tomato-> Target Spot</p1> : Target spot of tomato is caused by the fungal pathogen Corynespora cassiicola. The disease occurs on field-grown tomatoes in tropical and subtropical regions of the world. The initial foliar symptoms are pinpoint-sized, water-soaked spots on the upper leaf surfaces. The spots develop into small, necrotic lesions that have light brown centers and dark margins.</p>
        <p><p1>25. Tomato-> Tomato Yellow Leaf Curl Virus</p1> : Tomato yellow leaf curl is a disease of tomato caused by Tomato yellow leaf curl virus. Symptoms of TYLCV infection include severe stunting, reduction of leaf size, upward cupping/curling of leaves, chlorosis on leaves and flowers, and reduction of fruit production.</p>
        <p><p1>26. Tomato-> Tomato mosaic virus</p1> : Tomato mosaic virus (ToMV) is a plant pathogenic virus. Tomato mosaic virus (ToMV) can cause yellowing and stunting of tomato plants resulting in loss of stand and reduced yield. ToMV may cause uneven ripening of fruit, further reducing yield. Tobacco mosaic virus (TMV) was once thought to be more common on tomato. </p>
      </div>
    );
  }
}
